Issue 2 cadastro cliente
lanchesjaamp/dotlanche pull request #15
Opened 2024-05-19 14:26 UTC by angcostaneto

2024-05-19 18:31 UTC, atcorrea requested changes

2024-05-19 18:31 UTC, atcorrea commented on Core/DotLanches.Domain/Entities/Cliente.cs
>  public class Cliente
Cara, pelo que me lembro, precisamos cadastrar o e-mail do cliente também

2024-05-19 18:31 UTC, atcorrea commented on Core/DotLanches.Domain/Entities/Cliente.cs
> +        if (string.IsNullOrEmpty(Cpf))
Aqui, além de validar se está vazio, poderíamos validar se tem 11 caracteres também, pra não aceitar dado inválido

2024-05-20 22:53 UTC, angcostaneto commented on Core/DotLanches.Domain/Entities/Cliente.cs
>  public class Cliente
Feito

2024-05-20 22:54 UTC, angcostaneto commented on Core/DotLanches.Domain/Entities/Cliente.cs
> +        if (string.IsNullOrEmpty(Cpf))
Feito

2024-05-20 23:51 UTC, atcorrea approved these changes

2024-05-20 23:51 UTC, merged